### ISSUE TITLE
Not being able to flash AROMA zip on treble A/B devices like OP6 or U12+ (imagine)

### ISSUE THREAD

**Issue by jeanrivera** [amarullz/AROMA-Installer#38]
while trying to flash any AROMA GUI Installer embedded zip for example a ROM or OpenGapps, TWRP just freezes but adb commands still work it looks like a graphics rendering issue because it doesn't even get to the splash part of any zip with AROMA GUI I can provide logs if needed,

I know AROMA is an abandoned project but some of the ROM devs still use it for personal customizations on custom ROMs like Team Venom, LeeDroid, etc.... & Kernels like Elemental X

[recovery (4).log](https://github.com/amarullz/AROMA-Installer/files/2280239/recovery.4.log)

**Comment by jeanrivera** [comment]
not sure if anyone is following this issue at all but I just wanted to update just in case someone wants to give it a shot and fix the issue 

"The problem is that your device/TWRP is using DRM graphics (hardware accelerated) instead of framebuffer (traditional SW rendering). Aroma doesn't understand how to use your graphics "driver".

Unless you can get a build of TWRP (and kernel) with classic framebuffer rendering, it can't be fixed. Not sure how likely or even possible that is."

that being said if someone want to fix AROMA and with the proper drivers instructions for this new devices that would be awesome since most kernel dev will not go back to classic framebuffer having this new drivers

**Comment by aaaol** [comment]
I also encountered this problem.

I don't know how to solve it.

**Comment by twaik** [comment]
When I tried to solved that I noted that AROMA can't output to the screen even if TWRP got SIGSTOP. But you can clear the screen if you execute the "stop recovery" comand. TWRP will be stopped but AROMA will be able to use screen.

**Comment by jeanrivera** [comment]
And how do I execute the stop recovery command?

**Comment by twaik** [comment]
run_program("stop", "recovery");
Or
run_program("setprop", "ctl.stop", "recovery");

Also you shoul not forget about starting the recovery service right after the end of AI script. Use start or setprop ctl.start. Also you can reboot device without returning to recovery with "reboot -f system".

**Comment by jeanrivera** [comment]
@twaik what device you use for that?

**Comment by twaik** [comment]
@jeanrivera I don't remember. It was a long time ago. Try to run the command over ADB first.

**Comment by jeanrivera** [comment]
@twaik I did already, and it didn't work, I just got a black screen, this is more related to new display drivers on SD 845 devices, and aroma does not know how handle those graphics at all but thanks for the suggestions

**Comment by twaik** [comment]
@jeanrivera can you please try something for me? 
0. Use ADB.
1. Stop recovery. The screen should be black after this.
2. On the PC unpack update-binary to any folder.
3. Push update-binary and update.zip into / via ADB.
4. Try to start Aroma Installer update.zip manually
`/update-binary 1 1 /update.zip`
That is the comand used to start update process in recovery.
And then report about what you see on screen. If that fails we can't help you. 
Also I can try to create TWRP based graphics output for AROMA Installer, but it will work if the binary will be built inside TWRP source with other parts of recovery for device.

**Comment by jeanrivera** [comment]
C:\ADB>adb push update.zip /
update.zip: 1 file pushed. 29.2 MB/s (4164094 bytes in 0.136s)

C:\ADB>adb push update-binary /
update-binary: 1 file pushed. 27.1 MB/s (627580 bytes in 0.022s)

C:\ADB>adb shell /update-binary 1 1 /update.zip
/sbin/sh: /update-binary: Permission denied

C:\ADB>

**Comment by CaptainThrowback** [comment]
@jeanrivera
`adb shell chmod 755 /update-binary`
and then try that last command again

**Comment by jeanrivera** [comment]
this was the output on the command window but the device was on a black screen nothing visual

```
C:\ADB>adb push update.zip /
update.zip: 1 file pushed. 29.1 MB/s (4164094 bytes in 0.136s)

C:\ADB>adb push update-binary /
update-binary: 1 file pushed. 28.4 MB/s (627580 bytes in 0.021s)

C:\ADB>adb shell chmod 755 /update-binary

C:\ADB>adb shell /update-binary 1 1 /update.zip
aroma/s: Initializing
Starting AROMA Installer version 2.70RC2
     (c) 2013 by amarullz xda-developers
ui_print
ui_print Starting AROMA Installer version 2.70RC2
ui_print
ui_print (c) 2013 by amarullz xda-developers
ui_print
ui_print
aroma/s: Mute Parent
aroma/s: Saving Arguments
aroma/s: Open Archive
aroma/s: Initializing Resource
aroma/s: Opening Freetype
aroma/s: INDR Input Device: STM VL53L0 proximity sensor (event4) - Class : 0
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: snt8100fsr (event7) - Class : 6
aroma/s:   VKN : 0, CALIB : (0,1080,0,2560)
aroma/s: INDR Input Device: snt8100fsr (event2) - Class : 6
aroma/s:   VKN : 0, CALIB : (0,1080,0,2560)
aroma/s: INDR Input Device: qpnp_pon (event0) - Class : 1
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: gpio-keys (event6) - Class : 1
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: qwerty (event1) - Class : 1
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: AK8789_HALL_SENSOR (event3) - Class : 1
aroma/s:   VKN : 0, CALIB : (0,0,0,0)
aroma/s: INDR Input Device: synaptics_dsx_touchscreen (event5) - Class : 7
aroma/s:   VKN : 0, CALIB : (0,1439,0,2879)
aroma/s: Starting Interface
aroma/s: aroma-config was UTF-8
aroma/s: # INCLUDE SCRIPT (language_select.edify)
aroma/s:   + language_select.edify was UTF-8
aroma/s: (2) Freetype fonts loaded as Font Family
aroma/s: (2) Freetype fonts loaded as Font Family
```

**Comment by CaptainThrowback** [comment]
I assume nothing on the device, then?

**Comment by jeanrivera** [comment]
> I assume nothing on the device, then?

nothing in the device correct

**Comment by twaik** [comment]
Looks like the only way to start Aroma on the device is to build it over TWRP sources with some patches...

**Comment by jeanrivera** [comment]
> Looks like the only way to start Aroma on the device is to build it over TWRP sources with some patches...

are you able to help with that?

**Comment by twaik** [comment]
@jeanrivera maybe. First thing I need is link to TWRP source used for the build and its version. If TWRP is build from source for the device, of course.

**Comment by twaik** [comment]
I have some work here, but I think I'll help you in a few days. And you should know that the Aroma build will be suitable only on that device model. I don't even know if it work on CWM.

**Comment by jeanrivera** [comment]
> @jeanrivera maybe. First thing I need is link to TWRP source used for the build and its version. If TWRP is build from source for the device, of course.

https://github.com/CaptainThrowback/android_device_htc_ime

is that the correct source @CaptainThrowback

**Comment by jeanrivera** [comment]
> I have some work here, but I think I'll help you in a few days. And you should know that the Aroma build will be suitable only on that device model. I don't even know if it work on CWM.

there is no rush with that I have been trying to figure this out for months, practically since the release of the device and TWRP for it

**Comment by jeanrivera** [comment]
@twaik let me now if you need anything else from my end to makes things easier on your side

**Comment by twaik** [comment]
@jeanrivera Can you please try to build that on you device tree?
https://github.com/twaik/AROMA-Installer/

**Comment by jeanrivera** [comment]
I have asked @CaptainThrowback to do it since I have no idea how to build stuff I'll let you know the outcome, he did mentioned this:
Captain_Throwback [4:56 PM]
it has to be built in the 5.1 tree, unless he's updated the tree to actually build with 8.1
it definitely fails on 5.1

I'll try it on 8.1

Jeanrivera [4:56 PM]
I see his tree has a few commits amarullz does not have

Captain_Throwback [4:56 PM]
but AROMA doesn't build 64-bit, as far as I know

Jeanrivera [5:01 PM]
ok if you try and it doesn't work I'll still thank you a lot for trying

Captain_Throwback [5:02 PM]
I only see one new patch in the source and it looks specific to this problem
so I believe 64-bit will still be an issue
just building it with the updated TWRP tree and his changes *should* fix the issue, presumably
but since it doesn't build in 5.1, there's probably some code tweaks needed

**Comment by CaptainThrowback** [comment]
@twaik 

I tried building your source in the android-5.1 minimal Omni tree (which uses TWRP's android-9.0 branch) but I'm getting errors. AROMA has to be built for arm, so I have to use an older tree (either 5.1 or 6.0) for it to actually compile. It does not, however, compile, with your updates, at least not in android-5.1:
```
In file included from external/aroma-installer/src/libs/aroma_graph.cpp:33:0:
bootable/recovery/minui/include/minui/minui.h:221:45: error: declaration of C function 'int ev_init(ev_callback, void*)' conflicts with
 int ev_init(ev_callback input_cb, void *data);
                                             ^
In file included from external/aroma-installer/src/libs/aroma_graph.cpp:30:0:
external/aroma-installer/src/libs/../aroma.h:712:9: error: previous declaration 'int ev_init()' here
 int     ev_init(void);
         ^
external/aroma-installer/src/libs/aroma_graph.cpp:34:8: error: 'GRSurface' does not name a type
 static GRSurface* aroma_surface;
        ^
external/aroma-installer/src/libs/aroma_graph.cpp: In function 'unsigned char ag_init()':
external/aroma-installer/src/libs/aroma_graph.cpp:319:3: error: 'aroma_surface' was not declared in this scope
   aroma_surface->width = gr_fb_width();
   ^
external/aroma-installer/src/libs/aroma_graph.cpp: In function 'void ag_refreshrate()':
external/aroma-installer/src/libs/aroma_graph.cpp:1085:11: error: 'aroma_surface' was not declared in this scope
   gr_blit(aroma_surface, 0, 0, aroma_surface->width, aroma_surface->height, 0, 0);
           ^
build/core/binary.mk:620: recipe for target '/data/Android/build/omni/android-5.1/out/target/product/m8/obj/EXECUTABLES/aroma_installer_intermediates/src/libs/aroma_graph.o' failed
make: *** [/data/Android/build/omni/android-5.1/out/target/product/m8/obj/EXECUTABLES/aroma_installer_intermediates/src/libs/aroma_graph.o] Error 1
make: *** Waiting for unfinished jobs....

```

**Comment by twaik** [comment]
I used libminui's api in the patch. That should work on both TWRP and CWM, but it still will be device specific build. It should work on any recovery version.

**Comment by CaptainThrowback** [comment]
@twaik 
How is the build device-specific?

**Comment by twaik** [comment]
That means that the binary built with my source will be suitable only for the device it was build for.
New commit is available. You can ask firmware maintainer to build it.

**Comment by CaptainThrowback** [comment]
@twaik 
I think you misunderstood my very vague question. I mean I looked at the code, and I don't see how it's device-specific. There's no way to lunch for the device that we need to use the binary with and build, because the AROMA source doesn't support 64-bit nor the 8.1 Android tree. The only way to get it to build is to use an older tree, like I previously stated. So if you're saying I have to build for the device we want to use the binary on, that's not currently possible.

At any rate, I'm still getting build errors:
```
external/aroma-installer/src/libs/aroma_minui.cpp:8:8: error: 'GRSurface' does not name a type
 static GRSurface* aroma_surface;
        ^
external/aroma-installer/src/libs/aroma_minui.cpp: In function 'void aroma_minui_init()':
external/aroma-installer/src/libs/aroma_minui.cpp:11:2: error: 'aroma_surface' was not declared in this scope
  aroma_surface->width = gr_fb_width();
  ^
external/aroma-installer/src/libs/aroma_minui.cpp: In function 'int aroma_minui_get_fb_width()':
external/aroma-installer/src/libs/aroma_minui.cpp:19:9: error: 'aroma_surface' was not declared in this scope
  return aroma_surface->width;
         ^
external/aroma-installer/src/libs/aroma_minui.cpp: In function 'int aroma_minui_get_fb_height()':
external/aroma-installer/src/libs/aroma_minui.cpp:23:9: error: 'aroma_surface' was not declared in this scope
  return aroma_surface->height;
         ^
external/aroma-installer/src/libs/aroma_minui.cpp: In function 'void* aroma_minui_get_data()':
external/aroma-installer/src/libs/aroma_minui.cpp:27:9: error: 'aroma_surface' was not declared in this scope
  return aroma_surface->data;
         ^
external/aroma-installer/src/libs/aroma_minui.cpp: In function 'void aroma_minui_flip()':
external/aroma-installer/src/libs/aroma_minui.cpp:31:10: error: 'aroma_surface' was not declared in this scope
  gr_blit(aroma_surface, 0, 0, aroma_surface->width, aroma_surface->height, 0, 0);
          ^
external/aroma-installer/src/libs/aroma_minui.cpp: In function 'int aroma_minui_get_fb_width()':
external/aroma-installer/src/libs/aroma_minui.cpp:20:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
external/aroma-installer/src/libs/aroma_minui.cpp: In function 'int aroma_minui_get_fb_height()':
external/aroma-installer/src/libs/aroma_minui.cpp:24:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
external/aroma-installer/src/libs/aroma_minui.cpp: In function 'void* aroma_minui_get_data()':
external/aroma-installer/src/libs/aroma_minui.cpp:28:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: some warnings being treated as errors
build/core/binary.mk:620: recipe for target '/data/Android/build/omni/android-5.1/out/target/product/m8/obj/EXECUTABLES/aroma_installer_intermediates/src/libs/aroma_minui.o' failed
make: *** [/data/Android/build/omni/android-5.1/out/target/product/m8/obj/EXECUTABLES/aroma_installer_intermediates/src/libs/aroma_minui.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by twaik** [comment]
@CaptainThrowback that is device specific because it is built with libminui. libminui uses libdrm of the target device.
I didn't try to build the x64 version. But I used the 8.1 tree's twrp source for build. What is the exact reason Aroma can not be built over 8.1 tree?

**Comment by twaik** [comment]
Can you give me comands needed to clone the device tree and to initialize build environment? Including lunch/breakfast comand. I need to build the source using the TWRP version used on the device.

**Comment by CaptainThrowback** [comment]
I'm using the minimal Omni android-8.1 device tree, shallow clone, from here:
[](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/tree/twrp-8.1)

This repo init command:
`repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1`

And then to build:
`cd <source-dir>; export ALLOW_MISSING_DEPENDENCIES=true; . build/envsetup.sh; lunch omni_ime-eng; mka aroma_installer`

**Comment by CaptainThrowback** [comment]
@twaik 
Here is the plethora of errors when trying to build for the U12+ in the 8.1 Android tree:
https://del.dog/yacimugala.makefile

**Comment by twaik** [comment]
@CaptainThrowback  I disabled NEON support for 64bit build. You can try to build it again.

**Comment by CaptainThrowback** [comment]
Yes, your latest changes build successfully. Now @jeanrivera needs to test it in TWRP.

**Comment by jeanrivera** [comment]
still black screen

[recovery.log](https://github.com/amarullz/AROMA-Installer/files/2407394/recovery.log)

**Comment by twaik** [comment]
@CaptainThrowback did you send him new update.zip?

**Comment by jeanrivera** [comment]
[aroma-2.70RC2.zip](https://github.com/amarullz/AROMA-Installer/files/2407397/aroma-2.70RC2.zip)
this is the zip I am using for testing

**Comment by jeanrivera** [comment]
I just replaced the update-binary with the file he send to me after renaming from aroma_installer to update-binary

**Comment by twaik** [comment]
@jeanrivera Can you try to stop recovery first?
https://github.com/amarullz/AROMA-Installer/issues/38#issuecomment-423348745

**Comment by twaik** [comment]
@jeanrivera any updates?

**Comment by jeanrivera** [comment]
black screen but i did noticed the screen blinked for less than split a second output:

```
`C:\ADB>adb push aroma-2.70RC2.zip /
aroma-2.70RC2.zip: 1 file pushed. 28.4 MB/s (4432139 bytes in 0.149s)

C:\ADB>adb push update-binary /
update-binary: 1 file pushed. 28.6 MB/s (1409360 bytes in 0.047s)

C:\ADB>adb shell chmod 755 /update-binary

C:\ADB>adb shell stop recovery

C:\ADB>adb shell /update-binary 1 1 /aroma-2.70RC2.zip
aroma/s: Initializing
Starting AROMA Installer version 2.70RC2
     (c) 2013 by amarullz xda-developers
ui_print
ui_print Starting AROMA Installer version 2.70RC2
ui_print
ui_print (c) 2013 by amarullz xda-developers
ui_print
ui_print
aroma/s: Mute Parent
aroma/s: Saving Arguments
aroma/s: Open Archive
aroma/s: Initializing Resource
Unknown format 875713089
Unknown format 875713089
Using drm graphics.


```



`

**Comment by jeanrivera** [comment]
> @jeanrivera any updates?

yes i just replied

**Comment by twaik** [comment]
In your recovery.log both drmModeSetCrtc and drmModePageFlip failed with error -13: Access denied. I thought it was because TWRP was DRM master but now it should not interrupt the output. Maybe that's mistake in my patches... Looks like we need help of TWRP's developers here.

**Comment by twaik** [comment]
Another way to use AROMA in TWRP is to build TWRP and kernel without DRM support, only with classic framebuffer rendering.

**Comment by jeanrivera** [comment]
> Another way to use AROMA in TWRP is to build TWRP and kernel without DRM support, only with classic framebuffer rendering.

I am pretty sure that was a point of discussion already, but since there is no recovery partition on Treble A/B devices TWRP is part of the boot.img, building with classic framebuffer would make TWRP really slow or something like that the devs mentioned or at leas that was what I understood out of the conversation, I am just a guinea pig trying everything devs throw at me regarding aroma possible solutions but I do not build anything I just test and provide logs

**Comment by twaik** [comment]
Maybe that's my mistake in the AROMA&minui source... I need somebody to check it out. 
Your screen blinked so maybe image updated but I didn't noticed the mistake in my code...

**Comment by jeanrivera** [comment]
@twaik I guess there is no more to test for now right? I understand that you are busy on another projects, if you come up with something else let me know and thanks for the time you spend on trying to fix an issue for a device you don't even own yourself, I really appreciate that.

**Comment by twaik** [comment]
I have an idea what should be done but that needs an additional interface inside TWRP which provides drawing surface to updater binary via Unix socket. I dont think TWRP developers will add it to the project.

**Comment by CaptainThrowback** [comment]
@twaik

Submit a patch for it to TWRP Gerrit and see if it gets approved. Either way, if the patch is created, it'll be possible to build an unofficial TWRP for the affected devices with the possibility of a working AROMA interface. That itself might convince the TWRP team to add it, provided it's coded properly and doesn't negatively impact anything else.

**Comment by jeanrivera** [comment]
@twaik  & @CaptainThrowback I could try to use an unofficial TWRP build on my U12+ built by either of you with suggested patches and make sure it doesn't affect any other functionality in a negative way before submitting the patch, I'll gladly help testing this before submission and provide feedback and logs as needed. Thanks again to both of you on trying to resolve an issue on a device none of of you have, I understand how difficult it could be trying to fix something blindly, and depend on someone else for testing,

**Comment by twaik** [comment]
@CaptainThrowback I've seen the minuitest module in the TWRP source. If it will work with TWRP launched we have a chance to fix it. Can you build the minuitest binary and send it to @jeanrivera ?

**Comment by CaptainThrowback** [comment]
@twaik
Binary built and sent over to @jeanrivera. I assume it'll run in TWRP, but he'll have to push it and see

**Comment by jeanrivera** [comment]
@twaik I already have the minuitest file,and @CaptainThrowback told me to push it to /sbin while booted into TWRP and chmod 755 but after that, I have no idea

**Comment by twaik** [comment]
After that you have to launch it via adb shell

**Comment by jeanrivera** [comment]
C:\ADB>adb shell /sbin/minuitest
CANNOT LINK EXECUTABLE "/sbin/minuitest": library "libminui.so" not found
libc: CANNOT LINK EXECUTABLE "/sbin/minuitest": library "libminui.so" not found
libc: Fatal signal 6 (SIGABRT), code -6 in tid 723 (minuitest), pid 723 (minuitest)
Aborted

C:\ADB>

**Comment by jeanrivera** [comment]
@twaik I am missing libminui.so  @CaptainThrowback said he will provide it to me as soon as I get that I will provide more feedback on this, thanks again for all of this.

**Comment by jeanrivera** [comment]
@twaik 

```
C:\ADB>adb push libminui.so /sbin
libminui.so: 1 file pushed. 17.6 MB/s (208664 bytes in 0.011s)

C:\ADB>adb shell chmod 644 /sbin/libminui.so

C:\ADB>adb shell /sbin/minuitest
libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 758 (minuitest), pid 758 (minuitest)
Segmentation fault

C:\ADB>
```

**Comment by jeanrivera** [comment]
just ran miuitest on recovery after adb shell stop recovery

and it worked
I got like all colors test

```
C:\ADB>adb shell /sbin/minuitest
Initializing graphics.
Unknown format 875713089
Unknown format 875713089
Using drm graphics.
Starting tests
Red
Green
Blue
White
4 colors, 1 in each corner
4 colors, vertical stripes
Gradients, 1 in each corner
White with RGB text
PNG test with /res/images/test.png
Exit graphics.
Done.

```
C:\ADB>

**Comment by jeanrivera** [comment]
here is how it looks, sorry that gif is not good, i'll link the actual video

https://drive.google.com/file/d/1KP2lFfOjtWkT9Zs4UC-WBsokAb_OIsAX/view?usp=sharing

**Comment by jeanrivera** [comment]
@twaik please tell me this means good news? or at least progress in the right direction

**Comment by twaik** [comment]
Yes. That's good news. I will try building aroma installer over minui again.

**Comment by jeanrivera** [comment]
> Yes. That's good news. I will try building aroma installer over minui again.

just to let you know the only thing that didn't show on the test was the test.png at the end of the test, first we thought it was because the file didn't exist there, but i placed an actual png there and ran the test and still did not show on screen, and I try with a larger png still did not show at the end of the test, not sure how important is that the test.png shows on screen for all this project

**Comment by jeanrivera** [comment]
@twaik I understand you are busy with other projects, when you have some time and decide to build aroma again, let me know as soon you come up with a new build for testing, I'll gladly provide logs and feedback as needed, thanks for your continuous support on this matter.

**Comment by aaaol** [comment]
Seems to have seen hope.

**Comment by jeanrivera** [comment]
@tbalden since you mentioned interest in aroma on U12+ you might want to take a look in the progress we have made already thanks to @twaik  & @CaptainThrowback

**Comment by jeanrivera** [comment]
@twaik I am sorry to ask you this please do not take this question as an ETA, I just want to know if you are still interested in this project, since I haven't heard from you in the last 5 days, at least just a heads up would be nice...., if you are no longer interested on this I do understand, since you do not even own the device, and I know it would be so complicated for testing, thanks in advance. and again I am sorry if I am being annoying and persistent with this.......

**Comment by twaik** [comment]
I'm still interested in the project. I'm trying to find a way to emulate drm or use it on pc. For now I have sources of AROMA filemanager & installer (https://github.com/twaik/AROMA-tools) that runs on x86.

**Comment by jeanrivera** [comment]
@twaik any updates? or haven't had a chance to test yet?

**Comment by twaik** [comment]
I am still busy with another project. I will start working on AROMA soon.

**Comment by jeanrivera** [comment]
@twaik thanks for your help it helped @mikalovtch to resolve issues with the HTC U12+ thanks to you and him we have a fully working AROMA environment, with the downside we need a modified TWRP to make it work

**Comment by Miustone** [comment]
Talked to a TWRP Dev. The Problem will be that Busybox isn't working on Modern Devices anymore (Snapdragons from 2017+ (835/845+)). They are using Toybox which isn't compatible with AROMA since it hasn't been updated since around 4 Years to make use of it... Think it's sad to say but AROMA is dead as long as we don't get Busybox working on Modern Device Recovery environments (Or a AROMA Update for Toybox usage). See: https://landley.net/toybox/help.html

Edit: Usual Updater scripts using Busybox for Mounting are also not working anymore (Faced it myself on My XASP Project here on GitHub). AOSP ROMs are using also Toybox Commands to work...

**Comment by amarullz** [comment]
Sorry for everyone... I am not active in android "recovery" environment anymore, actually I don't even flash, root and customize my phone anymore atleast for 3-4 years :D, I have many things to do. And I dont follow latest android "rom" development anymore.

But I willing to restore the project, but I dont wanna play around too much in android system. I don't even know that "Busybox isn't working on Modern Devices anymore" thats so scary :) how long did I leave this environment.

I still develop enterprise Android app, I still using libaroma in my projects (embedded, realtime ui, etc), so I am able to devel some UI stuffs, but If there no one help me with android recovery programming (how it should install, what it need to flash, format, etc), I don't think I can do it anymore,,... I also don't have rooted phone, only have 1 phone with alot of important data I can't mess with.

**Comment by Miustone** [comment]
This is the best Message i've read in a while! I'm a huge fan of Your work @amarullz and worked since the very early Days with AROMA including the last Beta in the last few Years. I'm pretty sure if You would start a Thread or post something on XDA that People will buy or pay You any Device that You want to own. I would also like to Donate and give You a way to get back into Business :)

I would also be happy to share any Infos with You that could help to get back in. If You want to, check My Website and You will find a AROMA Installer ZIP from this Month. That's how it was working on My Mi Mix 2 Device with TWRP while it wasn't working for Mi 8, Poco F1 and Mi 9 Users. It also uses the great AROMA FM within the Installer which was hardcore to realize for Me back some Years... ^^

LINK: https://sites.google.com/view/miustone/RELEASES

**Comment by jeanrivera** [comment]
> Sorry for everyone... I am not active in android "recovery" environment anymore, actually I don't even flash, root and customize my phone anymore atleast for 3-4 years :D, I have many things to do. And I dont follow latest android "rom" development anymore.
> 
> But I willing to restore the project, but I dont wanna play around too much in android system. I don't even know that "Busybox isn't working on Modern Devices anymore" thats so scary :) how long did I leave this environment.
> 
> I still develop enterprise Android app, I still using libaroma in my projects (embedded, realtime ui, etc), so I am able to devel some UI stuffs, but If there no one help me with android recovery programming (how it should install, what it need to flash, format, etc), I don't think I can do it anymore,,... I also don't have rooted phone, only have 1 phone with alot of important data I can't mess with.

I could help out on testing part, and provide logs

**Comment by zyr-chan** [comment]
It has been more than a year since the last comment. Any updates?

**Comment by MLXProjects** [comment]
> 
> 
> It has been more than a year since the last comment. Any updates?

AROMA Installer uses the "old engine" to work, somebody need to adapt libaroma (the new engine) and still then it will have some issues because of being outdated (but is better than installer).

**Comment by ShashaankHari** [comment]
> I am still busy with another project. I will start working on AROMA soon.

im trying to build aroma file manager for ginkgo (Redmi note 8), and getting a lot of errors, ive not forked but i need help as i am very new to all the stuff.. could you help in the free time...
currently have devices tress and build twrp just with a few commands, yet to test the twrp build...

**Comment by ShashaankHari** [comment]
> > It has been more than a year since the last comment. Any updates?
> 
> AROMA Installer uses the "old engine" to work, somebody need to adapt libaroma (the new engine) and still then it will have some issues because of being outdated (but is better than installer).

I am willing to spend time in reviving this project, but i need help...

**Comment by MLXProjects** [comment]
> I am willing to spend time in reviving this project, but i need help...

Whoa, nice to read that! I'm also working on the same, can you contact me on Telegram? (@mlxprojects)

**Comment by ShashaankHari** [comment]
> > I am willing to spend time in reviving this project, but i need help...
> 
> Whoa, nice to read that! I'm also working on the same, can you contact me on Telegram? (@MLXProjects)

yes sure

**Comment by Miustone** [comment]
I found "maybe" something. Since newer Custom Recovery Builds does not contain Busybox but Toolbox and Toybox did i have Problems with My Scripts like:

`run_program("/sbin/busybox","unzip","/tmp/magisk/magisk.zip","META-INF/com/google/android/*","-d","/tmp/magisk");`
`run_program("/sbin/busybox","sh","/tmp/magisk/META-INF/com/google/android/update-binary","dummy","1","/tmp/magisk/magisk.zip");`

I solved this by adding:

`package_extract_file("META-INF/com/google/android/mars/busybox/busybox", "/sbin/busybox");`
`run_program("/sbin/chmod", "750", "/sbin/busybox");`

My Scripts can use Busybox now. Would this work for AROMA too? idk, just to lazy to try this yet... You can grab Busybox from here: https://github.com/Magisk-Modules-Repo/busybox-ndk
While i am not sure if one of them will work with AROMA... Give it a try...

**Comment by MLXProjects** [comment]
> 
> 
> I found "maybe" something. Since newer Custom Recovery Builds does not contain Busybox but Toolbox and Toybox did i have Problems with My Scripts like:
> 
> `run_program("/sbin/busybox","unzip","/tmp/magisk/magisk.zip","META-INF/com/google/android/*","-d","/tmp/magisk");`
> `run_program("/sbin/busybox","sh","/tmp/magisk/META-INF/com/google/android/update-binary","dummy","1","/tmp/magisk/magisk.zip");`
> 
> I solved this by adding:
> 
> `package_extract_file("META-INF/com/google/android/mars/busybox/busybox", "/sbin/busybox");`
> `run_program("/sbin/chmod", "750", "/sbin/busybox");`
> 
> My Scripts can use Busybox now. Would this work for AROMA too? idk, just to lazy to try this yet... You can grab Busybox from here: https://github.com/Magisk-Modules-Repo/busybox-ndk
> While i am not sure if one of them will work with AROMA... Give it a try...

well, the issue with AROMA Installer isn't busybox, but the "drivers" it has integrated to use the screen (which fail to start and make the installer crash). I'm still working on that, so don't worry!
